version: '3.8'
services:
  secs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secs-api
    restart: always
    ports:
      - 3004:3000
    networks:
      - network_nest
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 1234:5432
    networks:
      - network_nest
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db

networks:
  network_nest: